### ISSUE TITLE
ETS 1.35 - plugin not working

### ISSUE THREAD

**Issue by samsunix** [Hary309/hry-sic#1]
Hey

Thnx for amazing plugin, been using it for a long time. How ever it looks like it's not working anymore on ets 1.35, please, please, please update.

**Comment by Harry09** [comment]
Hi, Could you send `game.log.txt` file? This file is in `Documents/Euro Truck Simulator 2`. Thanks.

**Comment by Harry09** [comment]
But I am sure that the [recent version](https://github.com/Harry09/Smooth-Interior-Camera/releases/tag/1.3.1.0) of plugin works. Just delete all dlls in `plugins` folder and put there new version.

**Comment by samsunix** [comment]
Hey

Here's game.log
https://pastebin.com/8qQBxb58

I think I might got it working by editing controls.sii

 config_lines[206]: "mix trackiron `1 - (mouse.button_left?0 + keyboard.num4?0  | joy.pov1_left?0 + keyboard.num6?0 | joy.pov1_right?0 + keyboard.num7?0 + keyboard.num9?0)`"
 config_lines[207]: "mix trackiryaw `0.0`"
 config_lines[208]: "mix trackirpitch `-0.0`"
 config_lines[209]: "mix trackirroll `trackir.device.position.roll?0`"
 config_lines[210]: "mix trackirx `0.0`"
 config_lines[211]: "mix trackiry `0.0`"
 config_lines[212]: "mix trackirz `0.0`"

Camera turns smooth left and right but when released camera do instant jump back to front position.

**Comment by samsunix** [comment]
Hey

Here's game.log
https://pastebin.com/8qQBxb58

I think I might got it working by editing controls.sii

 config_lines[206]: "mix trackiron `1 - (mouse.button_left?0 + keyboard.num4?0  | joy.pov1_left?0 + keyboard.num6?0 | joy.pov1_right?0 + keyboard.num7?0 + keyboard.num9?0)`"
 config_lines[207]: "mix trackiryaw `0.0`"
 config_lines[208]: "mix trackirpitch `-0.0`"
 config_lines[209]: "mix trackirroll `trackir.device.position.roll?0`"
 config_lines[210]: "mix trackirx `0.0`"
 config_lines[211]: "mix trackiry `0.0`"
 config_lines[212]: "mix trackirz `0.0`"

Camera turns smooth left and right but when released camera do instant jump back to front position.

**Comment by Harry09** [comment]
I can't reproduce this bug. Sorry but I can't help.

**Comment by samsunix** [comment]
Hi, i would like to continue with this.

Same setup ets 2 v. 1.35.1.13s

I deleted sic_settings and launched game and now plugin kinda works

Camera turns smooth left and right but not center after release of button

- Samuli

**Comment by Harry09** [comment]
Did you check the keyboard settings? Maybe you have wrong key assigned

**Comment by samsunix** [comment]
I tried with camera turn left right and interior camera turn left right. It seems work only with interior camera. 
Also I get it autocenter but only by using trackir config I mentioned earlier. 

Do you have example config I could take a look and compare with?

**Comment by Harry09** [comment]
I mean keyboard settings in game. Just reset it. (ofc before, backup your config)
