### ISSUE TITLE
Keybind issue

### ISSUE THREAD

**Issue by cbaschnuller** [Hary309/hry-sic#3]
Your work is amazing thanks a lot for this amazing plugin. I have one little problem. I can`t set capslock as a keybind if i want to use the experimental features. This is my looking left bind in general.

**Comment by Hary309** [comment]
I looked into the code and it turned out that I missed support for this key, I will release today an update with the fix.

**Comment by Hary309** [comment]
I just released the fix, https://hary309.github.io/projects/hry-plugins/hry-sic
