### ISSUE TITLE
game crash when turning on plugin (Fixed)

### ISSUE THREAD

**Issue by PlayingGamez331** [Hary309/hry-sic#4]

**Comment by Hary309** [comment]
Send `game.crash.txt` and `game.log.txt` from `Documents/Euro Truck Simulator 2` or `Documents/American Truck Simulator` directory (depends on which game you launched)

**Comment by PlayingGamez331** [comment]
[game.crash.txt](https://github.com/Hary309/hry-sic/files/6249221/game.crash.txt)
[game.log.txt](https://github.com/Hary309/hry-sic/files/6249222/game.log.txt)

**Comment by Hary309** [comment]
Remove `hry_core` directory from `Documents`, and run game.

**Comment by PlayingGamez331** [comment]
thanks works great now

**Comment by Hary309** [comment]
Great!
