### ISSUE TITLE
can't open the main window

### ISSUE THREAD

**Issue by AyamPenyetKFC** [Hary309/hry-sic#5]
hai, thanks for creating this amazing plugins, but I have problem with this one, before I restore my computer with restore point this plugins works correctly but, after restoring my computer this plugins didn't works, I have tried to delete the plugins and inslall it again but, same can't open the main windows when I press delete button in (in game). thanks for your help.
[game.log.txt](https://github.com/Hary309/hry-sic/files/6257296/game.log.txt)
[game.crash.txt](https://github.com/Hary309/hry-sic/files/6257298/game.crash.txt)
[hry_core.log](https://github.com/Hary309/hry-sic/files/6257302/hry_core.log)

**Comment by Hary309** [comment]
Looks like problem with OneDrive sync directory.
It says:
```
[hry-core] remove: Access is denied.: "C:\Users\praja\OneDrive\Documents\hry_core\ets2/hry_core.log"
```
Maybe try to run ets2 as administrator or delete hry_core from Documents directory.

**Comment by AyamPenyetKFC** [comment]
thank you, it's work, the problems in my OneDrive folder access.
